name: 'build pikvm images'

on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  rpi4:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@main
      - name: 'Obtain pikvm codes'
        run: git clone https://github.com/pikvm/os
      - name: 'Build pikvm for rpi4'
        run: |
          cd os
          cp ../config.mk.rpi4 ./config.mk
          make os
          sudo make image
      - name: 'Clean install dependencies and build'
        run: |
          cd os
          ls | grep -v images | xargs -i sudo rm -rf {}
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pikvm-images
          path: ./os/images/
  pizerow:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@main
      - name: 'Obtain pikvm codes'
        run: git clone https://github.com/pikvm/os
      - name: 'Build pikvm for pizerow'
        run: |
          cd os
          cp ../config.mk.rpi0 ./config.mk
          make os
          sudo make image
      - name: 'Clean install dependencies and build'
        run: |
          cd os
          ls | grep -v images | xargs -i sudo rm -rf {}
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pikvm-images
          path: ./os/images/
