name: 'build pikvm images'

on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install dependency'
        run: sudo apt install git make curl binutils -y
      - name: 'Checkout codes'
        uses: actions/checkout@main
      - name: 'Obtain pikvm codes'
        run: git clone https://github.com/pikvm/os
      - name: 'Build pikvm for rpi4'
        run: |
          cd os
          cp ../config.mk.rpi4 ./config.mk
          make os
          sudo make image
      - name: 'Build pikvm for pizerow'
        run: |
          cd os
          cp ../config.mk.rpi0 ./config.mk
          make os
          sudo make image
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pikvm-images
          path: images/
      - name: 'Clean install dependencies and build'
        run: |
          cd .. && sudo rm -rf *
